repos:
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 26.3.1
  hooks:
  - id: black
    exclude: .tox, venv
- repo: https://github.com/PyCQA/isort
  rev: 9.0.0a3
  hooks:
  - id: isort
    files: .+\.py$
    exclude: .tox, venv
- repo: https://github.com/PyCQA/flake8
  rev: 7.3.0
  hooks:
  - id: flake8
    files: .+\.py$
    exclude: .tox, venv, migrations
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: debug-statements
    files: .+\.py$