name: python package

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        django: [
          "django>=3.2,<4.0",
          "django>=4.0,<4.1",
          "django>=4.1,<4.2",
          "django>=4.2,<5.0",
          "django>=5.0,<5.1",
          "django>=5.1,<5.2",
          "django>=5.2,<6.0",
        ]
        python: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
        exclude:
          # django 3.2
          - django: "django>=3.2,<4.0"
            python: "3.11"
          - django: "django>=3.2,<4.0"
            python: "3.12"
          - django: "django>=3.2,<4.0"
            python: "3.13"
          # django 4.0
          - django: "django>=4.0,<4.1"
            python: "3.7"
          - django: "django>=4.0,<4.1"
            python: "3.11"
          - django: "django>=4.0,<4.1"
            python: "3.12"
          - django: "django>=4.0,<4.1"
            python: "3.13"
          # django 4.1
          - django: "django>=4.1,<4.2"
            python: "3.7"
          - django: "django>=4.1,<4.2"
            python: "3.12"
          - django: "django>=4.1,<4.2"
            python: "3.13"
          # django 4.2
          - django: "django>=4.2,<5.0"
            python: "3.7"
          - django: "django>=4.1,<4.2"
            python: "3.13"
          # django 5.0
          - django: "django>=5.0,<5.1"
            python: "3.7"
          - django: "django>=5.0,<5.1"
            python: "3.8"
          - django: "django>=5.0,<5.1"
            python: "3.9"
          # django 5.1
          - django: "django>=5.1,<5.2"
            python: "3.7"
          - django: "django>=5.1,<5.2"
            python: "3.8"
          - django: "django>=5.1,<5.2"
            python: "3.9"
          # django 5.2
          - django: "django>=5.2,<6.0"
            python: "3.7"
          - django: "django>=5.2,<6.0"
            python: "3.8"
          - django: "django>=5.2,<6.0"
            python: "3.9"

    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: install pytest, pytest-django, django and impostor
        run: |
          pip install pytest==8.3.5 pytest-django==4.11.1
          pip install "${{ matrix.django }}"
          pip install -e .
      - name: run tests
        run: pytest -v tests/

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
      - name: install tox and any other packages
        run: |
          pip install flake8
      - name: lint with flake8
        run: |
          # stop the build if there are python syntax errors or undefined names
          flake8 . --count --select=e9,f63,f7,f82 --show-source --statistics
          # exit-zero treats all errors as warnings. the github editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: install coverage
        run: |
          pip install django pytest==8.3.5 pytest-django==4.11.1 pytest-cov==4.1.0
          pip install -e .
      - name: execute coverage
        run: |
          # execute tests with coverage
          pytest --cov-report=xml --cov=impostor tests/
          export codecov_token="${{ secrets.codecov_token }}"
          bash <(curl -s https://codecov.io/bash)